apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wibjds6n6-go
  janus-idp.io/tekton: wibjds6n6-go
  backstage.io/kubernetes-id: wibjds6n6-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wibjds6n6-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
