apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wibjds6n6-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wibjds6n6-go 
  name: wibjds6n6-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wibjds6n6-go 
